### ISSUE TITLE
Parsing is incorrect when having <meta> tagName

### ISSUE THREAD

**Issue by astoilkov** [inikulin/parse5#46] opened 2015-03-12 16:09 UTC
I have used the parse5.SimpleApiParser but when having a <meta> that is self closing the parser:
 1. Does not pass the selfClosing parameter to the startTag callback
 2. Does not call the endTag callback

```html
<meta charset="utf-8">
```

**Comment by inikulin** [comment] 2015-03-12 17:05
Duplicate of #39

**Closed by inikulin** 2015-03-12 17:05 UTC
