### ISSUE TITLE
HTML attributes without a value

### ISSUE THREAD

**Issue by frankps** [inikulin/parse5#205] opened 2017-07-15 09:49 UTC
Great library, but:
We need to manipulate Angular2 html files.
We have tags without values, for instance:
    <div attrNoValue></div>
When going through a parse + serialize sequence we always end up with:
    <div attrNoValue=""></div>
So, when the attribute didn't have a value, then the parse5 library will automatically add ="" to the right of the attribute. Can we instruct the serialize method that this shouldn't be done? Thx!

**Comment by inikulin** [comment] 2017-07-15 10:19
Duplicate of https://github.com/inikulin/parse5/issues/184.

**Closed by inikulin** 2017-07-15 10:19 UTC
Labels: duplicate
