### ISSUE TITLE
escapeString doesn't handle nulls/undefined

### ISSUE THREAD

**Issue by JohnGalt1717** [inikulin/parse5#203] opened 2017-06-21 15:29 UTC
This causes issues in angular and several other places where parse5 is used. Simply adding this to the escapeString function resolves the issue:

if (!str) return str;

It would be fantastic to get this resolved.

**Comment by RReverser** [comment] 2017-06-21 15:32
Thanks for the report. However, I believe this is a duplicate of https://github.com/inikulin/parse5/pull/145 where the answer was given.

**Comment by JohnGalt1717** [comment] 2017-06-21 15:48
Null is always a valid value for a string and should always be correctly handled.  It means no entry and an escaped no entry is still no entry not an error since null is a string.

We're not talking numbers or something, we're talking a valid state of the value passed.

Please reconsider and properly handle this.

**Comment by RReverser** [comment] 2017-06-21 15:52
> Null is always a valid value for a string and should always be correctly handled.

Why would you think so? `null` is a completely separate value, it's definitely not a string and TypeScript (which AFAIK Angular uses) with `strictNullChecks` or just `strict` mode will not allow you to pass it where a string exists.

This is an issue of consumer not passing the expected types, many things can go wrong in JavaScript when doing so.

**Closed by RReverser** 2017-06-21 15:52 UTC

**Comment by JohnGalt1717** [comment] 2017-06-21 16:02
I know so because this is computer science 101.

All strings are terminated with null (0x0). A string with no value is simply 0x0 but still has a pointer in memory to the initialized memory location.

Unassigned is different because it hasn't been assigned memory and thus would be an invalid value.

Strings unlike all other primative types can contain null and only null as a valid value because ALL strings are null terminated unlike all other primatives.

Thus passing null into anything that accepts a string value is valid in all programming languages ever. 

Parse5 ignores this basic principle of cs and isn't dealing with a valid state of a fully initialized variable.

Angular breaks with completely useless and unfixable errors (without endless trial and error) as a result of this and it isn't alone in his problem.

**Comment by domenic** [comment] 2017-06-21 16:08
Uh... you seem to be assuming all strings are C strings. Which are actually a sequence of bytes, terminated with the null (0x0) byte.

This is irrelevant and wrong in so many ways:

- This is not a computer science principle, it is a C programming language principle. (And one widely regarded as a mistake; see e.g. [this StackOverflow review](https://stackoverflow.com/questions/4418708/whats-the-rationale-for-null-terminated-strings).)
- C strings are not JavaScript strings
- JavaScript's `null` type is not a byte (or a string). It's a separate type. It has nothing to do with `0x0`, which in JavaScript is more properly represented by a *number*, like `let nullByte = 0`.

"Computer science 101" indeed, lol.

**Comment by RReverser** [comment] 2017-06-21 16:08
> All strings are terminated with null (0x0). A string with no value is simply 0x0 but still has a pointer in memory to the initialized memory location.

> Strings unlike all other primative types can contain null and only null as a valid value because ALL strings are null terminated unlike all other primatives.

This is JavaScript, strings are not zero-terminated here. I think you're confusing JavaScript strings with C strings which have very different representation.

Moreover, you're mixing `null` as a pointer, 0x0 as a byte and `null` as a JavaScript object value into one - they're all different things and different types. This is the reason why

> Thus passing null into anything that accepts a string value is valid in all programming languages ever.

is incorrect.

Btw, JavaScript is not the only one having non-zero-terminated representation for strings, see also Rust, Lua, and many others.

This is why

> I know so because this is computer science 101.
> Parse5 ignores this basic principle of cs

are incorrect - you're confusing computer science with implementation details of the other language you're coming from, which is irrelevant in current context.

**Comment by RReverser** [comment] 2017-06-21 16:12
Back to the topic:

> Angular breaks with completely useless and unfixable errors (without endless trial and error) as a result of this and it isn't alone in his problem.

I already explained above why `escapeString` doesn't *have to* check for types - it's responsibility of the library consumer.

However, there is also one deeper reason - if `escapeString` is called on `null`, it means that the AST is malformed in the first place and you got `null` as a value of some attribute or a text node which it could have never been when coming just from `parse5` (if it is, please do let us know and raise a separate issue!).

So this is just a symptop of a deeper bug in some transformer and it's indeed better for it to fail with a JavaScript error so that you could find the offending transformer and fix it, otherwise you can run into many more hidden issues than just during escaping.

**Comment by JohnGalt1717** [comment] 2017-06-21 17:46
@dominic etc.  You realize that JavaScript sits on top of c based software and is simply a scripting language controlling that c based software right? (Ie as is in the name, JavaScript is not a programming language it is a scripting language. Why?  Because it scripts the actions of other software. It does not interact with the processor directly ever.)

So in ALL cases of JavaScript, while you're not seeing the fact that the string is null terminated if you go and look in memory you will 100% see that it is null terminated.

Whether it should be or not is irrelivant. And if you don't think it should be then consider that almost every language has come out with nullable types specifically because "no entry" is entirely valid which of course is what this is about.

Escaping no entry is a valid request and of course the result back is no entry. In the case of angular this happens because the expression evaluates to a non string (ie false which is valid). So null is passed because there is no string to parse.

You can argue all you want that they should do the test for null before calling your function but the fact still remains that 0x0 is a valid string and your code doesn't handle a valid string and you're punting handling it upstream and causing bugs as a result.

**Comment by domenic** [comment] 2017-06-21 17:49
`0x0 === 0`, but `0x0 !== null`.

**Comment by fictitious** [comment] 2017-06-21 18:44
if you type this in the browser console:
```
typeof ''
```
it prints
```
"string"
```

if you  type this:
```
typeof null
```
it prints
```
"object"
```

if you type this:
```
typeof undefined
```

it prints

```
"undefined"
```

You see, javascript is weird, and technically, null is not a string (it's also not an object but that's irrelevant).

> You can argue all you want that they should do the test for null before calling your function but the fact still remains that 0x0 is a valid string

Whatever is valid is decided by whoever is defining the contract for the function in question, that is, the author of the library. Some authors like to support relaxed programming style and are content to handle whatever is thrown at them, some do not.

**Comment by RReverser** [comment] 2017-06-21 18:55
@JohnGalt1717 I believe everything that could be said on-topic here was already said and explained, so I'm going to go ahead and lock this issue to prevent future misunderstandings.
