### ISSUE TITLE
Parsing with parse5 SAXParser does not emit ending body and html tags

### ISSUE THREAD

**Issue by mdhaddad** [inikulin/parse5#136] opened 2016-06-06 20:10 UTC
For the attached html document (zipped) parsing with the SAXParser results in the ending body and html tokens not being emitted.

[1464054279593.7276865569.zip](https://github.com/inikulin/parse5/files/301241/1464054279593.7276865569.zip)

**Comment by inikulin** [comment] 2016-06-06 20:37
Can you add HTML code in issue instead of zip-archive, please?

**Comment by mdhaddad** [comment] 2016-06-06 22:41
The HTML file in question is over 800 KB. How do you want that added
instead of as a zip file?

**Comment by RReverser** [comment] 2016-06-06 23:34
@mdhaddad Remove all the unimportant parts (such as text or even attributes) and provide minimal exampe where your issue can be reproduced.

**Comment by mdhaddad** [comment] 2016-06-07 00:30
To be honest I'm not sure why the ending tokens for body and html are
not being emitted on this HTML document. It is from Bloomberg news,
presumably all their HTML article documents are like this. The
document is over 800KB so I'm not sure why the ending tokens are not
being emitted. I don't know where to begin in parsing it by hand to
get rid of supposedly non-relevant stuff.

I can provide the code I used for parse5 SAXParser to reproduce this
issue, so you can verify it on this document, but I don't know how to
parse the text of this document by hand to produce a "minimal"
example.

**Comment by inikulin** [comment] 2016-06-07 07:59
> The
document is over 800KB so I'm not sure why the ending tokens are not
being emitted. I don't know where to begin in parsing it by hand to
get rid of supposedly non-relevant stuff.

Using [bisection](https://en.wikipedia.org/wiki/Bisection_method) of the input and running parser on each iteration. Wort case shouldn't take more than ~20 iterations on input of this size.

**Comment by mdhaddad** [comment] 2016-06-07 13:12
Hmm, how would I effectively calculate the function value at the mid
point of an HTML file? Do I just chop it in half then feed the first
half to the parser, otherwise the second half? Anything of this sort
and the HTML file would be malformed.

**Comment by inikulin** [comment] 2016-06-07 13:47
> Hmm, how would I effectively calculate the function value at the mid
point of an HTML file?

???

> Do I just chop it in half then feed the first
half to the parser, otherwise the second half? Anything of this sort
and the HTML file would be malformed.

Just split content in `<body>` tag, should work just fine.

**Comment by mdhaddad** [comment] 2016-06-07 15:09
Ok I will do that (though the HTML file would still be malformed when
I split the content in the body tag in half, etc.)

**Comment by RReverser** [comment] 2016-06-07 15:10
You are having issues only with the end tag, so you likely shouldn't care about differences in tokens at the chunk boundaries in order to reproduce a bug.

**Comment by mdhaddad** [comment] 2016-06-07 22:37
Ok I got it down to an iframe in the content of the body tag (it happened to be the last iframe before the closing body tag) that did not have an closing iframe tag. This triggered the ending body and html tags not being emitted:

`<!DOCTYPE html><html xmlns:og="http://ogp.me/ns#" data-view-uid="0"><head></head> <body data-tracker-events="click,pageview"><iframe id="rufous-sandbox" scrolling="no" frameborder="0" allowtransparency="true" allowfullscreen="true" style="position: absolute; visibility: hidden; display: none; width: 0px; height: 0px; padding: 0px; border: none;"></body></html>`

**Comment by inikulin** [comment] 2016-06-07 22:55
OK, thank you for the simplified example. This is a by design behavior: when parser encounters `<iframe>` it parses it's content as a text. Here is an example: http://astexplorer.net/#/bz2uxPtBGp
As you can see `</body>` parsed as a text node. You will see similar behavior in browsers. 
This page markup is non-conforming: seems like they forgot to close `<iframe>` but it doesn't have visible effects because parser impilcitly emits closing `</body>` and `</html>` anyway.

**Closed by inikulin** 2016-06-07 22:55 UTC

**Comment by mdhaddad** [comment] 2016-06-07 23:01
Weird. Though don't browsers have to parse iframe contents as more
than just simple text if they are to render them correctly? How come
parse5 doesn't parse iframe contents as more than merely text as well?
Is that more work than the project is prepared to handle?

**Comment by RReverser** [comment] 2016-06-07 23:47
> Weird. Though don't browsers have to parse iframe contents as more than just simple text if they are to render them correctly?

No. Whenever in doubt, best is to consult the spec for the correct behavior:  https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inbody

```
A start tag whose tag name is "iframe"

    Set the frameset-ok flag to "not ok".

    Follow the generic raw text element parsing algorithm.
```

**Comment by RReverser** [comment] 2016-06-07 23:51
Also, you can use parser built-in into your browser to check the results:

```javascript
> new DOMParser().parseFromString('<iframe></body></html>', 'text/html').querySelector('iframe').textContent
"</body></html>"
```
