### ISSUE TITLE
Uppercase in attributes not preserved after parsing.

### ISSUE THREAD

**Issue by Supamiu** [inikulin/parse5#133] opened 2016-05-31 13:53 UTC
When parsing some Angular2 components, attributes like `*ngIf`, `*ngFor`, `*ngForOf` are not parsed with the uppercase, creating a template syntax error in the resulting html component.

Example:
```
var test = parse5.parseFragment('<div *ngIf="true"></div>');
console.log(treeAdapters.default.getFirstChild(test).attrs);
console.log(parse5.serialize(test));
```

output:
```
[ { name: '*ngif', value: 'true' } ]
<div *ngif="true"></div>
```

**Comment by domenic** [comment] 2016-05-31 14:38
Yep, this is how browsers work (and thus how parse5 works). That is why the Angular team had to invent their entire own "HTML" parser.

**Comment by RReverser** [comment] 2016-05-31 14:47
Closing as basically a duplicate of #116.

**Comment by Supamiu** [comment] 2016-05-31 14:48
So it's basically impossible to preserve uppercase in html attribute using parse5? I really need this feature for html editing (adding attributes to some tags for i18n purpose).

**Closed by RReverser** 2016-05-31 14:47 UTC

**Comment by RReverser** [comment] 2016-05-31 14:51
@Supamiu It's just not how HTML works. Angular 2 uses own templating language, so if you want to parse it, you most likely need to find and use the parser they do.

**Comment by Supamiu** [comment] 2016-05-31 15:04
@RReverser 

> It has proven itself reliable in such projects as jsdom, Angular2, Polymer and many more.

source: [README.md](https://github.com/inikulin/parse5/blob/master/README.md)

I thought you were the parser used by angular2. I'll start looking for their parser then.

**Comment by inikulin** [comment] 2016-05-31 15:30
> I thought you were the parser used by angular2. I'll start looking for their parser then.

https://github.com/angular/angular/blob/master/package.json#L90

But seems like it's not used to parse their HTML-like syntax

**Comment by RReverser** [comment] 2016-05-31 16:09
Looks like their one is here: https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/html_parser.ts (plus related modules like `html_lexer` and so)
