### ISSUE TITLE
Style attribute in inline css not parsing properly if properties which contains more than one values are present.

### ISSUE THREAD

**Issue by ratnajeetshyamkunwar** [inikulin/parse5#242] opened 2018-03-21 06:18 UTC
Eg. `<div style={color: #fff; font-size: 20px}></div>`
  will parse as =>```
{
          "nodeName": "div",
          "tagName": "div",
          "attrs": [
            {
              "name": "style",
              "value": "color: #fff; font-size: 20px"
            }
          ],..........
          }
```

but `<div style="color: #fff; font-family: 'Times New Roman', Times, serif'">`
will parse as ===>
```
{
          "nodeName": "div",
          "tagName": "div",
          "attrs": [
            {
              "name": "style",
              "value": "color: #fff; font-family: "
            },
            {
              "name": "times",
              "value": ""
            },
            {
              "name": "new",
              "value": ""
            },
            {
              "name": "roman',",
              "value": ""
            },
            {
              "name": "times,",
              "value": ""
            },
            {
              "name": "serif'",
              "value": ""
            }
          ], .......
}

```
Here you can see that the style attribute is not parsing properly.

**Comment by inikulin** [comment] 2018-03-22 12:59
Hi,

I can't reproduce this issue: https://runkit.com/embed/gy9ps7mf4564
Closing for now. Will be happy to reopen once you provide reproducible example.

**Closed by inikulin** 2018-03-22 12:59 UTC
