### ISSUE TITLE
question: escaped character automatically convert to normal charactor

### ISSUE THREAD

**Issue by Jocs** [inikulin/parse5#249] opened 2018-05-25 03:39 UTC
#### Hi, first of all thank you for creating such an excellent tool.

I'm the author of [Mark Text](https://github.com/marktext/marktext/). We use parse5 in Mark Text to parse HTML. However, a small problem was discovered during use. It was not known whether it was a bug or a feature.

For example, the following Node：

```markdown
<p>hello &gt; world</p>
```

will be automatically converted to this below:

![xxx](https://user-images.githubusercontent.com/9712830/40524967-16ecc122-6010-11e8-879e-48b5f4d78065.jpg)

And the `&gt;` is automatically converted to `>`, but what I want is still `&gt;`, So is this a bug or feature?

**Comment by RReverser** [comment] 2018-05-25 12:04
It's working as intended and duplicate of previous reports as you can find here: https://github.com/inikulin/parse5/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+entities

**Closed by RReverser** 2018-05-25 12:04 UTC

**Comment by Jocs** [comment] 2018-05-25 12:35
@RReverser is there any that does not convert escaped character to normal character in parse5?
