### ISSUE TITLE
Type definitions are not properly generated and typescript compile fails

### ISSUE THREAD

**Issue by hoancea** [inikulin/parse5#913] opened 2023-04-24 14:00 UTC
If I use the `parse5` module in a new `npm` package and then run a typescript compile, I get errors from the inside the `.d.ts` files from the `parse5` module. The compiler is complaining about the keyword `type` being included inside the brackets next to the import statements, and the compile succeeds if I manually remove those.

For example, inside `index.d.ts` in the published version, the first line is:
`import { type ParserOptions } from './parser/index.js';`
I manually adjusted this to:
`import { ParserOptions } from './parser/index.js';`
After applying this change in all `.d.ts` files, I was able to run typescript compile on my project.

I made a [small project](https://github.com/inikulin/parse5/files/11311188/parse5-test.zip) where I was able to replicate the issue. You should run into the same issue after running `npm i && tsc`. I am also uploading my [output](https://github.com/inikulin/parse5/files/11311235/tsc.log) from running `tsc`.

Versions used:
* node 18.14.2
* npm 9.5.0
* typescript 4.4.3

**Comment by wooorm** [comment] 2023-04-24 14:04
Update TypeScript. Your TypeScript is very old.

Duplicate of 878.

**Closed as not planned** 2023-04-25 07:46 UTC
