### ISSUE TITLE
Parse5 does not typecheck values

### ISSUE THREAD

**Issue by tarjei** [inikulin/parse5#291] opened 2019-04-15 07:56 UTC
```
const { JSDOM } = require('jsdom')

var jsdom = require('jsdom')

var jsdom = new jsdom.JSDOM(
  `<div>
      <progress
        class="StudyPlan-load-progress svelte-g1ijzk"
        value="0"
        max="100"
      />
    </div>`,
  {
    url: 'http://localhost',
    pretendToBeVisual: true,
  }
)
var window = jsdom.window

window.document.querySelector('.StudyPlan-load-progress').value = 0

console.log(window.document.body.innerHTML)
```

Output:

```
$ node /tmp/testcase.js
0
/tmp/node_modules/parse5/lib/serializer/index.js:168
    str = str.replace(AMP_REGEX, '&amp;').replace(NBSP_REGEX, '&nbsp;');
              ^

TypeError: str.replace is not a function
    at Function.Serializer.escapeString (/tmp/node_modules/parse5/lib/serializer/index.js:168:15)
    at Serializer._serializeAttributes (/tmp/node_modules/parse5/lib/serializer/index.js:103:38)
    at Serializer._serializeElement (/tmp/node_modules/parse5/lib/serializer/index.js:67:14)
    at Serializer._serializeChildNodes (/tmp/node_modules/parse5/lib/serializer/index.js:50:26)
    at Serializer._serializeElement (/tmp/node_modules/parse5/lib/serializer/index.js:93:18)
    at Serializer._serializeChildNodes (/tmp/node_modules/parse5/lib/serializer/index.js:50:26)
    at Serializer.serialize (/tmp/node_modules/parse5/lib/serializer/index.js:36:14)
    at Object.exports.serialize (/tmp/node_modules/parse5/lib/index.js:28:23)
    at htmlSerialization (/tmp/node_modules/jsdom/lib/jsdom/living/domparsing/serialization.js:20:17)
    at module.exports.fragmentSerialization (/tmp/node_modules/jsdom/lib/jsdom/living/domparsing/serialization.js:27:12)

```

**Comment by RReverser** [comment] 2019-04-15 10:02
Duplicate of #145.

**Comment by tarjei** [comment] 2019-04-15 10:04
@RReverser so this is mor an issue of JSDOM then?

**Comment by RReverser** [comment] 2019-04-15 10:23
To be honest, I'm not familiar with JSDOM API enough to give a definite answer. @domenic could you chime in perhaps?

**Comment by domenic** [comment] 2019-04-15 13:17
The code in the OP appears to use jsdom and not use parse5, so yes, filing it on the jsdom repository would make more sense to me.

**Comment by RReverser** [comment] 2019-04-15 13:44
@domenic Thanks!

**Closed by RReverser** 2019-04-15 13:44 UTC

**Comment by tarjei** [comment] 2019-04-15 17:27
I've filed the issue against jsdom, but I'm still not entirely convinced that the issue is not a parse5 bug based on the what I get back when testing this in the browser (see the image at the bottom of https://github.com/jsdom/jsdom/issues/2554 )
