### ISSUE TITLE
parse5-html-rewriting-stream fails on file > 128kByte

### ISSUE THREAD

**Issue by petercmuc** [inikulin/parse5#820] opened 2023-02-13 16:40 UTC
We use Angulars devkit server to serve HTML during development.
If the file exceeds a certain size (128kByte) the out of parse5-html-rewriting-stream is truncated.

It looks like the handling of chunks  in '_getRawHtml':
```
    private _getRawHtml(location: Token.Location): string {
        const { droppedBufferSize, html } = this.tokenizer.preprocessor;
        const start = location.startOffset - droppedBufferSize;
        const end = location.endOffset - droppedBufferSize;

        return html.slice(start, end);
    }
```

The value for "start" becomes negative in that case....

I have created a setup for angular for demonstration: https://github.com/petercmuc/angular-devkit-server-error

**Comment by fb55** [comment] 2023-02-13 23:08
This seems to be a duplicate of https://github.com/inikulin/parse5/issues/292, which has been fixed a couple of releases ago. Can Angular update its dependency?

**Closed** 2023-02-14 11:06 UTC

**Comment by petercmuc** [comment] 2023-02-14 11:38
The problem is probably the same, but the original bug was about the 64k limit. I only see the bug when the file exceeds 128k!

I have also created a bug in Angular: https://github.com/angular/angular-cli/issues/24707

**Comment by petercmuc** [comment] 2023-02-23 12:42
Hi @fb55 
angular-cli has updated their dependency to  "parse5-html-rewriting-stream": "7.0.0"
I have updated the above test project with the new angular version for reproducing the issue:
```
ng-serve@0.0.0 angular-devkit-server-error
└─┬ @angular-devkit/build-angular@15.2.0
  └── parse5-html-rewriting-stream@7.0.0
```

Unfortunately the problem is still not fixed!
