### ISSUE TITLE
str.replace is not a function with Angular 4 and server side rendering with Universal

### ISSUE THREAD

**Issue by ghego1** [inikulin/parse5#216] opened 2017-10-03 09:48 UTC
I'm using Angular 4 with server side rendering powered by Angular Universal.

When trying to render the app on the node server, however, I get this error:

```
TypeError: str.replace is not a function
    at Function.Serializer.escapeString (/Users/.../node_modules/parse5/lib/serializer/index.js:36:10)
```

The problem is generated by the fact that the renderer passes to `Serializer.escapeString` non string values.

To prevent this from crashing the app, I've edited like so `Serializer.escapeString`:

```
Serializer.escapeString = function( str, attrMode ) {
  if ( typeof str === 'string' ) str = str
    .replace( AMP_REGEX, '&amp;' )
    .replace( NBSP_REGEX, '&nbsp;' );

  if ( typeof str === 'string' && attrMode )
    str = str.replace( DOUBLE_QUOTE_REGEX, '&quot;' );

  else if ( typeof str === 'string' ) {
    str = str
      .replace( LT_REGEX, '&lt;' )
      .replace( GT_REGEX, '&gt;' );
  }

  return str;
};
```

Can this be merged in a future bux fix?

**Comment by inikulin** [comment] 2017-10-03 10:10
Duplicate of https://github.com/inikulin/parse5/pull/145

**Closed by inikulin** 2017-10-03 10:10 UTC
