### ISSUE TITLE
I got an error in safari 10.0.1

### ISSUE THREAD

**Issue by xbl** [inikulin/parse5#250] opened 2018-05-31 05:30 UTC
## error:
```
ReferenceError: Can't find variable: $
```
error line :
```
function isAsciiLower(cp) {
    return cp >= $.LATIN_SMALL_A && cp <= $.LATIN_SMALL_Z;
}
```

## my code:
``` javascript

import parse5 from 'parse5';

const setAttrFn = (documentFragment, attrObj) => {
  documentFragment.childNodes.forEach((node) => {
    if (!node.tagName) return;
    node.attrs.push(attrObj);
    setAttrFn(node, attrObj);
  });
};

export const parseHtml = (htmlStr, attrObj) => {
  // this line well error
  const documentFragment = parse5.parseFragment(htmlStr);
  setAttrFn(documentFragment, attrObj);
  return parse5.serialize(documentFragment);
};

```

chrome、pc safari  is ok, but in my old iphone safari 10.0.1 is not fine.
can you help me ?

use the parse5 version is **5.0.0**
And I try the parse5 version 4.0.0 is ok!

**Comment by inikulin** [comment] 2018-06-11 21:53
Closing since the problem is definitely in the way you bundle parse5 for browser. Sorry, I can't even help you with any suggestion since the provided information is not sufficient to make any assumptions.

**Closed by inikulin** 2018-06-11 21:53 UTC
Labels: question
