### ISSUE TITLE
Suggestion: Incremental Parsing

### ISSUE THREAD

**Issue by rbuckton** [inikulin/parse5#201] opened 2017-06-14 18:25 UTC
Following on to #200, re-parsing a large HTML (or in this case, _ecmarkup_) document after a text edit can be fairly expensive. It would be great to expose an incremental parser capable of re-using unmodified AST subtrees with only the necessary edits applied.

**Comment by inikulin** [comment] 2017-06-16 11:26
Hi,

Thank you for the suggestion. I have thoughts about implementing language services suitable for usage in editors for some time now. The problem is that I don't have experience in editors development to figure out required capabilities for such parse5 API. 

I guess incremental parser will be a good first step towards this direction, but I'm interested in established practices that are used for such parsers for other languages. I have some ideas already, but I would like to avoid inventing a bicycle. 

Also, I've noted that you mentioned a tree, so I guess you need a full AST and token stream will not work for you? The problem with full incremental parsing is that already parsed nodes are not invariant in HTML and can be modified by consequent input. Therefore, invalidation of the subtree can be a computationally expensive task, and hence ruin any advantages of the incremental parsing. Whereas, simple token stream don't have such limitations. 

On the other hand, we can build simplified AST that avoids quirky error recovery mechanisms, but suitable for usage in editors, which brings us back to the idea of the [LexicalTreeParser](https://github.com/inikulin/parse5/issues/132). 

To conclude, I would really like to learn more about this domain area before jumping to the actual implementation. Any details/discussion on this topic will be definitely appreciated.

**Comment by RReverser** [comment] 2017-06-16 15:41
Incremental parsing is indeed a very complicated task, especially in languages where single character can change entire input after that. You need to know where you're in the tree to detect whether added characters can modify the content after that or not. On another hand, once you know the user is editing e.g. inside of attribute value, it's relatively easy to detect whether you need to reparse all the following content or given characters can just change attribute value in-place.

**Comment by fb55** [comment] 2022-03-30 00:23
If someone is looking for a library that supports incremental parsing, you might want to have a look at https://github.com/tree-sitter/tree-sitter-html

This feature would require considerable changes within parse5, and I don't have the sense that there is a lot of demand for it. Closing this as out of scope.

**Closed** 2022-03-30 00:23 UTC
Labels: enhancement
